swagger: "2.0"
info:
    title: AD Service
    description: This service provides the AD service
    version: 0.0.1
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /ad:
        get:
            tags:
                - advertise
            summary: List all ADs by filter
            description: List all ADs by filter
            operationId: advertise#list_ads
            parameters:
                - name: offset
                  in: query
                  description: Offset of AD
                  required: true
                  type: integer
                  default: 0
                  minimum: 0
                - name: limit
                  in: query
                  description: Limit of AD
                  required: true
                  type: integer
                  default: 5
                  minimum: 1
                - name: age_start
                  in: query
                  description: Start age of target
                  required: false
                  type: integer
                  maximum: 100
                  minimum: 1
                - name: age_end
                  in: query
                  description: End age of target
                  required: false
                  type: integer
                  maximum: 100
                  minimum: 1
                - name: gender
                  in: query
                  description: Gender of target
                  required: false
                  type: string
                  enum:
                    - M
                    - F
                - name: country
                  in: query
                  description: Country of target
                  required: false
                  type: string
                  enum:
                    - TW
                    - JP
                - name: platform
                  in: query
                  description: Platform of target
                  required: false
                  type: string
                  enum:
                    - ios
                    - android
                    - web
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/AdResponse'
            schemes:
                - http
        post:
            tags:
                - advertise
            summary: Create a new AD
            description: Create a new edge
            operationId: advertise#create_ad
            parameters:
                - name: create_ad_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AdvertiseCreateAdRequestBody'
                    required:
                        - title
                        - start_at
                        - end_at
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/AdvertiseCreateAdResponseBody'
                        required:
                            - id
            schemes:
                - http
definitions:
    AdResponse:
        title: AdResponse
        type: object
        properties:
            end_at:
                type: string
                description: End time of AD
                example: "2024-12-10T03:00:00.000Z"
                format: date-time
            title:
                type: string
                description: Title of AD
                example: AD 1
                minLength: 1
                maxLength: 100
        description: List all ads by filter
        example:
            end_at: "2024-12-10T03:00:00.000Z"
            title: AD 1
        required:
            - title
            - end_at
    AdvertiseCreateAdRequestBody:
        title: AdvertiseCreateAdRequestBody
        type: object
        properties:
            conditions:
                type: object
                properties:
                    age_end:
                        type: integer
                        description: End age of target
                        example: 60
                        format: int64
                        minimum: 1
                        maximum: 100
                    age_start:
                        type: integer
                        description: Start age of target
                        example: 18
                        format: int64
                        minimum: 1
                        maximum: 100
                    country:
                        type: string
                        description: Country of target
                        example: TW
                        enum:
                            - TW
                            - JP
                    gender:
                        type: string
                        description: Gender of target
                        example: M
                        enum:
                            - M
                            - F
                    platform:
                        type: string
                        description: Platform of target
                        example: ios
                        enum:
                            - ios
                            - android
                            - web
                example:
                    age_end: 60
                    age_start: 18
                    country: TW
                    gender: M
                    platform: ios
            end_at:
                type: string
                description: End time of AD
                example: "2024-12-10T03:00:00.000Z"
                format: date-time
            start_at:
                type: string
                description: Start time of AD
                example: "2024-03-10T03:00:00.000Z"
                format: date-time
            title:
                type: string
                description: Title of AD
                example: AD 1
                minLength: 1
                maxLength: 100
        example:
            conditions:
                age_end: 60
                age_start: 18
                country: TW
                gender: M
                platform: ios
            end_at: "2024-12-10T03:00:00.000Z"
            start_at: "2024-03-10T03:00:00.000Z"
            title: AD 1
        required:
            - title
            - start_at
            - end_at
    AdvertiseCreateAdResponseBody:
        title: AdvertiseCreateAdResponseBody
        type: object
        properties:
            id:
                type: integer
                description: ID of the AD
                example: 34
                format: int64
        example:
            id: 34
        required:
            - id
